"""Add customer and credit fields to WalletTransaction

Revision ID: ebce428f82d8
Revises: 589f4f257220
Create Date: 2026-08-02 07:58:22.505174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebce428f82d8'
down_revision: Union[str, None] = '589f4f257220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('is_credit', sa.Boolean(), nullable=False))
    op.add_column('wallet_transactions', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_wallet_transactions_customer_id'), 'wallet_transactions', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'wallet_transactions', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_transactions_customer_id'), table_name='wallet_transactions')
    op.drop_column('wallet_transactions', 'customer_id')
    op.drop_column('wallet_transactions', 'is_credit')
    # ### end Alembic commands ###
