"""remove_commission_from_wallet_transactions

Revision ID: ffbcedee1470
Revises: a007f2ab8b7e
Create Date: 2026-08-03 13:09:21.573085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbcedee1470'
down_revision: Union[str, None] = 'a007f2ab8b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('commission', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
