"""Add opening_balance to WalletAccount

Revision ID: 589f4f257220
Revises: 001
Create Date: 2026-08-02 07:37:10.410489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589f4f257220'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cash_closings_cash_opening_id_key'), 'cash_closings', type_='unique')
    op.drop_index(op.f('ix_cash_closings_cash_opening_id'), table_name='cash_closings')
    op.create_index(op.f('ix_cash_closings_cash_opening_id'), 'cash_closings', ['cash_opening_id'], unique=True)
    op.drop_constraint(op.f('cash_openings_opening_date_key'), 'cash_openings', type_='unique')
    op.drop_index(op.f('ix_cash_openings_opening_date'), table_name='cash_openings')
    op.create_index(op.f('ix_cash_openings_opening_date'), 'cash_openings', ['opening_date'], unique=True)
    op.drop_constraint(op.f('currency_buy_transactions_transaction_number_key'), 'currency_buy_transactions', type_='unique')
    op.drop_index(op.f('ix_currency_buy_transactions_transaction_number'), table_name='currency_buy_transactions')
    op.create_index(op.f('ix_currency_buy_transactions_transaction_number'), 'currency_buy_transactions', ['transaction_number'], unique=True)
    op.drop_constraint(op.f('currency_sell_transactions_transaction_number_key'), 'currency_sell_transactions', type_='unique')
    op.drop_index(op.f('ix_currency_sell_transactions_transaction_number'), table_name='currency_sell_transactions')
    op.create_index(op.f('ix_currency_sell_transactions_transaction_number'), 'currency_sell_transactions', ['transaction_number'], unique=True)
    op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('wallet_accounts', sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False))
    op.drop_constraint(op.f('wallet_transactions_transaction_number_key'), 'wallet_transactions', type_='unique')
    op.drop_index(op.f('ix_wallet_transactions_transaction_number'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_transaction_number'), 'wallet_transactions', ['transaction_number'], unique=True)
    op.drop_constraint(op.f('wallet_types_code_key'), 'wallet_types', type_='unique')
    op.drop_index(op.f('ix_wallet_types_code'), table_name='wallet_types')
    op.create_index(op.f('ix_wallet_types_code'), 'wallet_types', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_types_code'), table_name='wallet_types')
    op.create_index(op.f('ix_wallet_types_code'), 'wallet_types', ['code'], unique=False)
    op.create_unique_constraint(op.f('wallet_types_code_key'), 'wallet_types', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_wallet_transactions_transaction_number'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_transaction_number'), 'wallet_transactions', ['transaction_number'], unique=False)
    op.create_unique_constraint(op.f('wallet_transactions_transaction_number_key'), 'wallet_transactions', ['transaction_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('wallet_accounts', 'opening_balance')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_unique_constraint(op.f('system_settings_key_key'), 'system_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_currency_sell_transactions_transaction_number'), table_name='currency_sell_transactions')
    op.create_index(op.f('ix_currency_sell_transactions_transaction_number'), 'currency_sell_transactions', ['transaction_number'], unique=False)
    op.create_unique_constraint(op.f('currency_sell_transactions_transaction_number_key'), 'currency_sell_transactions', ['transaction_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_currency_buy_transactions_transaction_number'), table_name='currency_buy_transactions')
    op.create_index(op.f('ix_currency_buy_transactions_transaction_number'), 'currency_buy_transactions', ['transaction_number'], unique=False)
    op.create_unique_constraint(op.f('currency_buy_transactions_transaction_number_key'), 'currency_buy_transactions', ['transaction_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_openings_opening_date'), table_name='cash_openings')
    op.create_index(op.f('ix_cash_openings_opening_date'), 'cash_openings', ['opening_date'], unique=False)
    op.create_unique_constraint(op.f('cash_openings_opening_date_key'), 'cash_openings', ['opening_date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_closings_cash_opening_id'), table_name='cash_closings')
    op.create_index(op.f('ix_cash_closings_cash_opening_id'), 'cash_closings', ['cash_opening_id'], unique=False)
    op.create_unique_constraint(op.f('cash_closings_cash_opening_id_key'), 'cash_closings', ['cash_opening_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
