"""Add due_date to Credit

Revision ID: e7ab7e1fa985
Revises: ebce428f82d8
Create Date: 2026-08-02 08:04:57.103468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ab7e1fa985'
down_revision: Union[str, None] = 'ebce428f82d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits', 'due_date')
    # ### end Alembic commands ###
