"""drop unused settings, credit, and wallet_transaction_item tables

Revision ID: 09415a616624
Revises: ffbcedee1470
Create Date: 2026-08-11 14:57:30.163032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09415a616624'
down_revision: Union[str, None] = 'ffbcedee1470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_credit_payments_created_by', table_name='credit_payments')
    op.drop_index('ix_credit_payments_credit_id', table_name='credit_payments')
    op.drop_index('ix_credit_payments_deleted_at', table_name='credit_payments')
    op.drop_index('ix_credit_payments_payment_date', table_name='credit_payments')
    op.drop_table('credit_payments')
    op.drop_index('ix_credits_created_by', table_name='credits')
    op.drop_index('ix_credits_credit_type', table_name='credits')
    op.drop_index('ix_credits_customer_id', table_name='credits')
    op.drop_index('ix_credits_deleted_at', table_name='credits')
    op.drop_index('ix_credits_status', table_name='credits')
    op.drop_table('credits')
    op.drop_index('ix_wallet_transaction_items_deleted_at', table_name='wallet_transaction_items')
    op.drop_index('ix_wallet_transaction_items_wallet_transaction_id', table_name='wallet_transaction_items')
    op.drop_table('wallet_transaction_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transaction_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('wallet_transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['wallet_transaction_id'], ['wallet_transactions.id'], name='wallet_transaction_items_wallet_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_transaction_items_pkey')
    )
    op.create_index('ix_wallet_transaction_items_wallet_transaction_id', 'wallet_transaction_items', ['wallet_transaction_id'], unique=False)
    op.create_index('ix_wallet_transaction_items_deleted_at', 'wallet_transaction_items', ['deleted_at'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credit_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('remaining_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='credits_created_by_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='credits_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credits_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_credits_status', 'credits', ['status'], unique=False)
    op.create_index('ix_credits_deleted_at', 'credits', ['deleted_at'], unique=False)
    op.create_index('ix_credits_customer_id', 'credits', ['customer_id'], unique=False)
    op.create_index('ix_credits_credit_type', 'credits', ['credit_type'], unique=False)
    op.create_index('ix_credits_created_by', 'credits', ['created_by'], unique=False)
    op.create_table('credit_payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='credit_payments_created_by_fkey'),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], name='credit_payments_credit_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credit_payments_pkey')
    )
    op.create_index('ix_credit_payments_payment_date', 'credit_payments', ['payment_date'], unique=False)
    op.create_index('ix_credit_payments_deleted_at', 'credit_payments', ['deleted_at'], unique=False)
    op.create_index('ix_credit_payments_credit_id', 'credit_payments', ['credit_id'], unique=False)
    op.create_index('ix_credit_payments_created_by', 'credit_payments', ['created_by'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###
