"""Add wallet ids to currency transactions

Revision ID: a007f2ab8b7e
Revises: e7ab7e1fa985
Create Date: 2026-08-02 08:11:44.862519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a007f2ab8b7e'
down_revision: Union[str, None] = 'e7ab7e1fa985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_buy_transactions', sa.Column('mmk_wallet_id', sa.UUID(), nullable=False))
    op.add_column('currency_buy_transactions', sa.Column('thb_wallet_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_currency_buy_transactions_mmk_wallet_id'), 'currency_buy_transactions', ['mmk_wallet_id'], unique=False)
    op.create_index(op.f('ix_currency_buy_transactions_thb_wallet_id'), 'currency_buy_transactions', ['thb_wallet_id'], unique=False)
    op.create_foreign_key(None, 'currency_buy_transactions', 'wallet_accounts', ['mmk_wallet_id'], ['id'])
    op.create_foreign_key(None, 'currency_buy_transactions', 'wallet_accounts', ['thb_wallet_id'], ['id'])
    op.add_column('currency_sell_transactions', sa.Column('mmk_wallet_id', sa.UUID(), nullable=False))
    op.add_column('currency_sell_transactions', sa.Column('thb_wallet_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_currency_sell_transactions_mmk_wallet_id'), 'currency_sell_transactions', ['mmk_wallet_id'], unique=False)
    op.create_index(op.f('ix_currency_sell_transactions_thb_wallet_id'), 'currency_sell_transactions', ['thb_wallet_id'], unique=False)
    op.create_foreign_key(None, 'currency_sell_transactions', 'wallet_accounts', ['mmk_wallet_id'], ['id'])
    op.create_foreign_key(None, 'currency_sell_transactions', 'wallet_accounts', ['thb_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_sell_transactions', type_='foreignkey')
    op.drop_constraint(None, 'currency_sell_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_currency_sell_transactions_thb_wallet_id'), table_name='currency_sell_transactions')
    op.drop_index(op.f('ix_currency_sell_transactions_mmk_wallet_id'), table_name='currency_sell_transactions')
    op.drop_column('currency_sell_transactions', 'thb_wallet_id')
    op.drop_column('currency_sell_transactions', 'mmk_wallet_id')
    op.drop_constraint(None, 'currency_buy_transactions', type_='foreignkey')
    op.drop_constraint(None, 'currency_buy_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_currency_buy_transactions_thb_wallet_id'), table_name='currency_buy_transactions')
    op.drop_index(op.f('ix_currency_buy_transactions_mmk_wallet_id'), table_name='currency_buy_transactions')
    op.drop_column('currency_buy_transactions', 'thb_wallet_id')
    op.drop_column('currency_buy_transactions', 'mmk_wallet_id')
    # ### end Alembic commands ###
